scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false
        lower_threshold: 0.30
        upper_threshold: 12.0

    # filter2:
    #   name: angel_filter
    #   type: laser_filters/LaserScanAngularBoundsFilter
    #   params:
    #     lower_angle: -3.14  #
    #     upper_angle: -0.5  #
